site_name: cloudatlas.blog
site_url: https://cloudatlas.blog

theme:
  name: material

  features:
    - navigation.tabs        # Enables horizontal navigation
    - navigation.top         # Ensures the navigation is at the top
    - navigation.instant     # Improves loading speed for tabs
    - navigation.expand      # Expands navigation on small screens for better usability
  palette:           # High-contrast slate scheme
    primary: indigo
    accent: indigo             # Teal for better contrast with indigo
  font:
    text: Roboto             # Consistent, clean sans-serif font
    code: Roboto Mono        # Monospace font for code
  icon:
    logo: material/library
  logo: images/logo.jpeg     # Custom logo for the site
  favicon: images/favicon.ico # Add a favicon for a polished look

extra_css:
  - assets/styles/custom.css # Custom CSS for advanced styling

nav:
  - Home: index.md
  - Consulting:
      - Consulting Services: consulting/consulting-services.md
  - AI for Business Executives:
      - AI for Business: ai-for-business/ai-for-business.md
  - Writing:
      - AI Investments: writing/ai-investments.md
      - Diffusion Transformers: writing/diffusion-transformers.md
      - DSPy: writing/dspy.md
      - Gaming AI: writing/gaming-ai.md
      - Graph Neural Networks: writing/graph-neural-networks.md
      - Graph RAG: writing/graph-rag.md
      - Reinforcement Learning: writing/reinforcement-learning.md
      - State Space Models: writing/state-space-models.md
  - Books:
      - Books: books/books.md
  - GraphRAG:
      - GraphRAG: graphrag/graphrag.md

plugins:
  - search
