site_name: My Documentation
theme:
  name: material
  palette:
    primary: indigo
    accent: blue
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    logo: material/library  # You can replace this with another Material icon or upload a custom one.
  logo: images/logo.png  # Add a custom logo image in your `docs/images` folder

nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - DSpy (2410):
    - Introduction: dspy/overview.md
    - Installation: dspy/getting-started.md
    - Examples: dspy/examples.md

  - Graph RAG (2411): 
    - Introduction: graph-rag/overview.md
    - Knowledge Graphs: graph-rag/knowledge-graph.md
    - Building a Knowledge Graph : graph-rag/knowledge-graph.md
    - GraphRAG : graph-rag/graph-rag.md
    - Graph Index vs RDF Graph db : graph-rag/graph-index-vs-rdf.md
    - LLM Grounding with GraphRAG : graph-rag/grounding.md
    - LLM Reasoning with GraphRAG : graph-rag/reasoning.mde
    - GraphAttention with GNN's: graph-rag/graph-attention.md
  - Project Layout: project-layout.md

